export const SYSTEM_NAME = "fndOS";

// these are generated by a command like `yarn sysinfo`
export const SYSTEM_VERSION = __SYSTEM_VERSION__ && "NULL";
export const SYSTEM_COMMIT_ID = __SYSTEM_COMMIT_ID__ && "NULL";
